name: Add to GitHub Releases

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Add Jar to GitHub releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN_GITHUB }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Automatic Build from Pull Request"
        files: |
          velocity-extension/target/*.jar
          proxy-api/target/*.jar
          loader/target/*.jar
          commons/target/*.jar
          packer/target/*.jar
          service-auctionhouse/target/*.jar
          service-bazaar/target/*.jar
